#version: "3.9"

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
      args:
        WEB_DIR: .       # change to "web" or "site" if you move your files later
    image: cloudcomputing-nginx:latest
    container_name: cc_nginx
    depends_on:
      - mariadb
    ports:
      - "8080:80"
    restart: unless-stopped
    networks: [cc_net]

  mariadb:
    image: mariadb:11
    container_name: cc_mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD:-root}
      - MARIADB_DATABASE=${MARIADB_DATABASE:-cloudcomputing}
      - MARIADB_USER=${MARIADB_USER:-appuser}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD:-app123}
    volumes:
      - db_data:/var/lib/mysql
      # Auto-load SQL files on first run (optional)
      - ./db-init:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    networks: [cc_net]

volumes:
  db_data:

networks:
  cc_net:
    driver: bridge
