name: Build & Push Nginx Image

on:
  push:
    branches: ["**"]
    paths:
      - "Dockerfile.nginx"
      - "nginx.conf"
      - "**/*.html"
      - "**/*.css"
      - "**/*.js"
      - "**/*.png"
      - "**/*.jpg"
      - "**/*.jpeg"
      - "**/*.svg"
      - "docker-compose.yml"
      - "docker-compose.prod.yml"
      - "Makefile"
      - ".dockerignore"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-nginx
  BRANCH_TAG: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.BRANCH_TAG }}
            type=raw,value=latest,enable=${{ endsWith(github.ref, 'refs/heads/main') || endsWith(github.ref, 'refs/heads/master') }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.nginx
          push: true
          build-args: |
            WEB_DIR=.
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
